services:
  marketplace_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8088:8088'
    environment:
      - PORT=8088
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src
      