FROM node:latest

WORKDIR /usr/src/app

COPY . .
COPY ./.env.production ./.env

RUN npm install

RUN npm run build

RUN rm -rf ./src

EXPOSE 8080

# npm run start:prod
CMD [ "npm" , "run", "start:prod" ]